### ISSUE TITLE
Increase the namber of scaffold?

### ISSUE THREAD

**Issue by TakashiKoyama** [mandricigor/scaffmatch#1]
Hi,

First of all, I appreciate you to distribute such a nice tool.
I have a question regarding result of ScaffMatch.
I tried to scaffold my de novo assembled genome using BAC-end sequences from Sanger.
The original number of scaffold was 358,189 and after scaffolding with ScaffMatch, I got 364,297 scaffolds.
I think the number of scaffold should decrease after scaffolding.
Could you tell me why?

Thank you for your kind helps.

best,
Takashi

**Comment by mandricigor** [comment]
Hi Takashi,

thank you for trying our tool. Could you please provide me more information
regarding your reads and assembly (contigs)? Like read length, insert or
fragment length, read orientation, etc.?

Thanks.

2016-01-30 17:12 GMT+02:00 TakashiKoyama notifications@github.com:

**Comment by TakashiKoyama** [comment]
Thank you for your quick reply.
OK. I will try to provide some information regarding my situation.
1. Read length
   Since I got BESs by Sanger, the read length is apex. 600 to 700bp.
2. Insert length
   The average insert length of my BAC clones are apx. 120kb. I don't know how deviate it is.
3. Read orientation
   FR ( -> [ insert DNA apx. 120kb ] <- )

Is these are the ones you asked? If you need more information, Please let me know.

best,
Takashi

**Comment by mandricigor** [comment]
Thank you for the information. 120kb insert length is kind of big one :) I
have never tried to run the tool on such insert lengths. Can you please
tell me how many reads were aligned to the contigs?

Or, in ideal case, if you can share your input with me, I could do a more
thorough investigation. I would appreciate if you sent me your reads and
contigs.

Thanks.

2016-01-30 17:41 GMT+02:00 TakashiKoyama notifications@github.com:

**Comment by TakashiKoyama** [comment]
OK. I will mail you if I prepare my data.
Since my data is relatively large and our network is slow, it will take several hours to be prepared.
Sorry for your inconvenience.

Takashi

**Comment by TakashiKoyama** [comment]
Hi,

I now mailed you from my hotmail account.
If you need more details, please let me know.
Thanks!

Takashi

**Comment by mandricigor** [comment]
Thank you very much, Takashi,

I will analyze it.

2016-01-31 6:15 GMT+02:00 TakashiKoyama notifications@github.com:

**Comment by TakashiKoyama** [comment]
Thanks for Igor's advice, I could solve this issue.
I really appreciate for his helps!
