### ISSUE TITLE
mapped.txt file is empty

### ISSUE THREAD

**Issue by bennend** [mandricigor/scaffmatch#2]
Hi, 

I was using Scaffmatch for scaffolding the assembled Pacbio contigs (assembled by smartdenovo) with PE reads sequenced from Illumina (Inset size is 270bp, read length is 150bp). And here is the script:
`scaffmatch -w ~/WDCM_test/ScaffMatch/DK002 -c DK002/*Choose.assembly.fa -1 DK002/1.Cleandata/*IS270_Clean.1.fq.gz -2 DK002/1.Cleandata/*IS270_Clean.2.fq.gz -i 270 -p fr -s 67`
Everything works well and no error is reported, but the mapped file.txt is empty and the Scaffold number、Total length、N50 length of the scaffolds generated are the same as the Scaffold number、Total length、N50 length of the contigs in the input contigs file. Any help is appreciated!

Best

Ben

**Comment by mandricigor** [comment]
Hi Ben,
are you using gzipped fastq files? Try first to extract them. Please let me know what you get.
Thanks,
Igor

**Comment by bennend** [comment]
Hi Igor,

I've unzipped the fq files and rerun the script, but still the mapped.txt file, multiple.txt, same.txt and unmapped.txt are empty. Here are some statistics of the input contigs: Total Length (bp): 3,343,941; N50 Length (bp):1,674,504; Gap Number (bp):0. Could here be any other reasons?

Best

Ben

**Comment by mandricigor** [comment]
Hi Ben,
sorry for a late reply. Basically, everything looks ok, you got your
scaffolds. Probably, the line which outputs the mapped reads is commented
out. If you really need the mapped reads I can correct it for you.
Thanks,
Igor

пт, 11 янв. 2019 г. в 00:43, bennend <notifications@github.com>:

**Comment by bennend** [comment]
Hi Igor, 

Thank you for your reply, I think i'll just try with a different set of data. Thanks again.

Best,

Ben
